### PR TITLE
config api and 3rdparty

### PR DESCRIPTION
**Pull request by nattawut-netway**

### CODE REVIEW

**Comment by klaarnut** [comment]
Task linked: [CU-1zpp3rv api-server and 3rdparty-server](https://app.clickup.com/t/1zpp3rv)

**Review by pariwat-ezyadmin — APPROVED** [review]
OK

**Review by pariwat-ezyadmin — APPROVED** [review]
OK2

**Review by klaarnut — APPROVED** [review]
proved

**Pull request merged**
